name: sneakers_shop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for state management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          style: normal
        - asset: assets/fonts/JosefinSans-Italic.ttf
          style: italic
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/data.json

